# Generated by Django 3.1.7 on 2021-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210404_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teg',
            name='name',
            field=models.CharField(db_index=True, max_length=40, verbose_name='teg_name'),
        ),
    ]
