# Generated by Django 3.1.7 on 2021-04-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210404_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tegs',
            field=models.ManyToManyField(related_name='posts', to='blog.Teg'),
        ),
    ]
