# Generated by Django 3.1.7 on 2021-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210404_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teg',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='teg_name'),
        ),
    ]
