# Generated by Django 3.1.7 on 2021-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210404_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ['-published'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='post',
            name='tegs',
            field=models.ManyToManyField(related_name='posts', to='blog.Teg'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('title', 'content')},
        ),
    ]
