# Generated by Django 3.1.7 on 2021-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210410_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='section name')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='order')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='tegs',
        ),
        migrations.DeleteModel(
            name='Teg',
        ),
        migrations.CreateModel(
            name='MainSection',
            fields=[
            ],
            options={
                'verbose_name': 'MainSection',
                'verbose_name_plural': 'MainSections',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.section',),
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
            ],
            options={
                'verbose_name': 'teg',
                'verbose_name_plural': 'tegs',
                'ordering': ('main_section__order', 'main_section__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('blog.section',),
        ),
        migrations.AddField(
            model_name='section',
            name='main_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.mainsection', verbose_name='main section'),
        ),
        migrations.AddField(
            model_name='post',
            name='marker',
            field=models.ManyToManyField(related_name='posts', to='blog.Marker'),
        ),
    ]
