# Generated by Django 3.1.7 on 2021-04-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210412_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'ordering': ('main_section__order', 'main_section__name', 'order', 'name'), 'verbose_name': 'marler', 'verbose_name_plural': 'markers'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='marker',
            new_name='markers',
        ),
    ]
