# Generated by Django 3.1.7 on 2021-04-12 13:44

import blog.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210412_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.advuser', verbose_name='post author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=blog.utilities.create_filename, verbose_name='images'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to=blog.utilities.create_filename, verbose_name='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='blog.post', verbose_name='attachments')),
            ],
            options={
                'verbose_name': 'attacment',
                'verbose_name_plural': 'attacments',
                'default_related_name': 'attachments',
            },
        ),
    ]
