# Generated by Django 3.1.7 on 2021-04-12 14:00

import blog.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210412_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='images',
        ),
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(default=0, upload_to=blog.utilities.create_filename, verbose_name='image'),
            preserve_default=False,
        ),
    ]
